# Generated by Django 3.0.1 on 2020-01-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0005_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_cartType',
            field=models.CharField(max_length=250),
        ),
    ]
