# Generated by Django 3.0.1 on 2020-01-10 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0009_auto_20200110_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='donor_Acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donate.Donor'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='receiver_Acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Donate.Receiver'),
        ),
    ]
