# Generated by Django 3.0.1 on 2020-01-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0010_auto_20200110_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='donor_Acc',
            new_name='donor',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='receiver_Acc',
            new_name='receiver',
        ),
    ]
