# Generated by Django 3.0.1 on 2020-01-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0013_auto_20200110_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='users',
            field=models.ManyToManyField(to='Donate.User'),
        ),
    ]
