# Generated by Django 3.0.1 on 2020-01-10 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0014_donor_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='donor_Acc',
            new_name='donors',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='receiver_Acc',
            new_name='receivers',
        ),
    ]
