# Generated by Django 3.0.1 on 2020-01-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('contact', models.IntegerField(verbose_name=10)),
                ('totalAmt', models.IntegerField(verbose_name=50)),
                ('bankAcc', models.IntegerField(verbose_name=50)),
                ('donor_Acc', models.IntegerField(verbose_name=50)),
                ('receiver_Acc', models.IntegerField(verbose_name=50)),
            ],
        ),
    ]
