# Generated by Django 3.0.1 on 2020-01-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=50)),
                ('user_fullname', models.CharField(max_length=250)),
                ('user_DOB', models.DateField(verbose_name=50)),
                ('user_address', models.DateField(verbose_name=50)),
                ('user_contact', models.IntegerField(verbose_name=10)),
                ('user_age', models.IntegerField(verbose_name=10)),
            ],
        ),
    ]
