# Generated by Django 3.0.1 on 2020-01-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0004_auto_20200110_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('donor_Firstname', models.CharField(max_length=250)),
                ('donor_Middlename', models.CharField(max_length=250)),
                ('donor_Lastname', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('contact', models.IntegerField(verbose_name=10)),
                ('country', models.CharField(max_length=250)),
                ('postal_code', models.IntegerField(verbose_name=50)),
                ('state', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('donate_amt', models.IntegerField(verbose_name=50)),
                ('donor_cartType', models.IntegerField(verbose_name=50)),
                ('donor_acc', models.IntegerField(verbose_name=50)),
                ('donate_date', models.DateField(verbose_name=50)),
                ('card_id', models.IntegerField(verbose_name=10)),
                ('card_expirationDate', models.IntegerField(verbose_name=10)),
                ('comment', models.TextField()),
                ('verify', models.BooleanField(verbose_name=10)),
            ],
        ),
    ]
