# Generated by Django 3.0.1 on 2020-01-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0006_auto_20200110_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='card_expirationDate',
            field=models.DateField(),
        ),
    ]
