# Generated by Django 3.0.1 on 2020-01-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0008_receiver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiver',
            old_name='donor_fullname',
            new_name='full_name',
        ),
    ]
