# Generated by Django 3.0.1 on 2020-01-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_address',
            field=models.CharField(max_length=50),
        ),
    ]
