# Generated by Django 3.0.1 on 2020-01-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0007_auto_20200110_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('donor_fullname', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('contact', models.IntegerField(verbose_name=10)),
                ('distribute_catagories', models.CharField(max_length=250)),
                ('distribute_amt', models.IntegerField(verbose_name=15)),
                ('distribute_date', models.DateField(verbose_name=50)),
                ('receiver_acc', models.IntegerField(verbose_name=50)),
                ('distribute_handcash', models.IntegerField(verbose_name=50)),
            ],
        ),
    ]
