# Generated by Django 3.0.1 on 2020-01-10 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0011_auto_20200110_2031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='donor',
            new_name='donor_acc',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='receiver',
            new_name='receiver_acc',
        ),
    ]
