# Generated by Django 3.0.1 on 2020-01-10 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Donate', '0012_auto_20200110_2053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='donor_acc',
            new_name='donor_Acc',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='receiver_acc',
            new_name='receiver_Acc',
        ),
    ]
